# Generated by Django 4.1.7 on 2023-04-04 02:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinfo',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
