# Generated by Django 4.1.7 on 2023-04-04 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_bookinfo_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinfo',
            name='authorinfo',
        ),
        migrations.RemoveField(
            model_name='bookinfo',
            name='bookclass',
        ),
        migrations.RemoveField(
            model_name='bookinfo',
            name='bookisbn',
        ),
        migrations.RemoveField(
            model_name='bookinfo',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='bookinfo',
            name='image',
        ),
        migrations.RemoveField(
            model_name='bookinfo',
            name='ishot',
        ),
        migrations.RemoveField(
            model_name='bookinfo',
            name='moredesc',
        ),
        migrations.AddField(
            model_name='bookinfo',
            name='author',
            field=models.IntegerField(default=20, verbose_name='价格'),
        ),
    ]
